name: mn2y_lotto_gen
description: A simple lotto generator app
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  sqflite: ^2.0.0
  path_provider: ^2.0.0
  provider: ^6.0.0

flutter:
  uses-material-design: true

